### ISSUE TITLE
ondrej-sika.cz - remove PGP link from contact page

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/ondrejsikawebs#6]

**Comment by ondrejsika** [comment]
@zuzjes help @svatkova with the task, please 😄❤️

**Comment by zuzjes** [comment]
ok, ja to udelam

**Comment by ondrejsika** [comment]
To ne, at to prave udela Kata. Hezky ukol na zacatek. Ale bud ji k dispozici na pripadne dotazy :)

**Comment by zuzjes** [comment]
ok
